name       : tig
version    : 2.2.2
release    : 2
source     :
    - https://github.com/jonas/tig/archive/tig-2.2.2.tar.gz : 01a8e3ceb7aab9fd6298eccd6349cb7e813c4fc396d0da41e8c48edf6570c487
license    : GPL-2.0
component  : programming.tools
summary    : Text-mode interface for git
description: |
    Tig is an ncurses-based text-mode interface for git. It functions mainly as a Git repository browser, but can also assist in staging changes for commit at chunk level and act as a pager for output from various Git commands.
builddeps  :
    - pkgconfig(ncursesw)
    - asciidoc
    - xmlto
rundeps    :
    - git
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    %make install-doc-man DESTDIR="%installroot%"
