name       : tig
version    : 2.5.6
release    : 13
source     :
    - https://github.com/jonas/tig/releases/download/tig-2.5.6/tig-2.5.6.tar.gz : 50bb5f33369b50b77748115c730c52b13e79b2de49cba7167bb634eb683d965f
homepage   : https://jonas.github.io/tig/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Text-mode interface for git
description: |
    Tig is an ncurses-based text-mode interface for git. It functions mainly as a Git repository browser, but can also assist in staging changes for commit at chunk level and act as a pager for output from various Git commands.
builddeps  :
    - pkgconfig(ncursesw)
    - asciidoc
    - xmlto
rundeps    :
    - git
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install install-doc-man
    install -Dm00644 contrib/tig-completion.bash $installdir/usr/share/bash-completion/completions/tig
    install -Dm00644 contrib/tig-completion.zsh  $installdir/usr/share/zsh/site-functions/_tig
